apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique name of the Deployment instance
  name: my-mongo-app
  labels:
    app: mongo-app
spec:
  # Specify the desired number of replicas
  replicas: 4
  selector:
    matchLabels:
      app: mongo-app
  template:
    metadata:
      labels:
        # Apply this label to Pods to match the selector
        app: mongo-app
    spec:
      containers:
      - name: mongodb-app
        # Container image to run
        image: adarshmali/node-mongo-db:02
        ports:
        - containerPort: 3000 # Expose application port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: mongo-app
        # MongoDB container image
        image: adarshmali/monggo:01
        ports:
        - containerPort: 27017 # Expose MongoDB port

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-my-mongodb
spec:
  ports:
    # Accept traffic sent to port 80
    - name: tcp
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: mongo-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  