apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique name of the Deployment instance
  name: node-app
  labels:
    app: node-app
spec:
  # Specify the desired number of replicas
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        # Apply this label to Pods to match the selector
        app: node-app
    spec:
      containers:
      - name: node-app
        # Container image to run
        image: adarshmali/node-mongo-db:02
        ports:
        - containerPort: 3000 # Expose application port
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: service-node-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: mongo-app
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer

env:
  - name: MONGO_HOST
    value from:
    ConfigMapKeyRef:
    name: mongo-config
    key: MONGO_HOST
  - name: MONGO_PORT
    value from:
    ConfigMapKeyRef:
    name: mongo-config
    key: MONGO_PORT